---
# tasks file for roles/configure_vm_resource
- name: Generate VM template for {{ inventory_hostname }}
  delegate_to: localhost
  template:
    src: machine-template.xml.j2
    dest: ~/machine-template-{{ inventory_hostname }}.xml
  when: "'ocp4_nodes' in group_names"
  tags:
    - configure_vm_resource
    
- name: Defining VM for {{ inventory_hostname }}
  delegate_to: localhost
  virt:
    command: define
    xml: "{{ lookup('template','machine-template.xml.j2') }}"
  when: "'ocp4_nodes' in group_names" 
  tags:
    - configure_vm_resource
