---
# tasks file for roles/cleanup_storage
- name: Clean up qcow slow disk
  delegate_to: localhost
  file:
    path: '/var/lib/libvirt/images/{{ inventory_hostname }}.qcow2'
    state: absent
  when: vm_disktype == "slow"

- name: Clean up qcow fast disk
  delegate_to: localhost
  file:
    path: '/libvirt-nvme/{{ inventory_hostname }}.qcow2'
    state: absent
  when: vm_disktype == "fast"