kind: Service
apiVersion: v1
metadata:
  name: s3
  labels:
    app: noobaa
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 6001
      name: s3
    - port: 443
      targetPort: 6443
      name: s3-https
  selector:
    noobaa-s3: "true"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: noobaa-agent
  labels:
    app: noobaa
spec:
  selector:
    matchLabels:
      noobaa-module: noobaa-agent
  serviceName: noobaa-agent
  replicas: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: noobaa
        noobaa-module: noobaa-agent
        noobaa-s3: "true"
    spec:
      containers:
        - name: noobaa-agent
          readinessProbe:
            # https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
            # ready when s3 port is open
            tcpSocket:
              port: 6001
            timeoutSeconds: 5
          image: noobaa/noobaa-core:5.0.1-2dda7b3
          imagePullPolicy: IfNotPresent
          resources:
            # https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
            requests:
              cpu: "100m"
              memory: "500Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
          env:
            # Insert the relevant config for the current agent
            - name: CONTAINER_PLATFORM
              value: KUBERNETES
            - name: AGENT_CONFIG
              value: "eyJhZGRyZXNzIjoid3NzOi8vbm9vYmFhLW1nbXQubm9vYmFhLnN2Yy5jbHVzdGVyLmxvY2FsOjg0NDMvIiwicm91dGluZ19oaW50IjoiSU5URVJOQUwiLCJzeXN0ZW0iOiJub29iYWEiLCJjcmVhdGVfbm9kZV90b2tlbiI6ImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUpoWTJOdmRXNTBYMmxrSWpvaU5XUTBZVGd3TWprelpHUTBOall3TURJelpESmpPV1ExSWl3aWMzbHpkR1Z0WDJsa0lqb2lOV1EwWVRnd01qa3paR1EwTmpZd01ESXpaREpqT1dRMklpd2ljbTlzWlNJNkltTnlaV0YwWlY5dWIyUmxJaXdpWlhoMGNtRWlPbnNpWVdkbGJuUmZZMjl1Wm1sblgybGtJam9pTldRMFlUZ3hZV0V6WkdRME5qWXdNREl6WkRKak9XVmtJbjBzSW1GMWRHaHZjbWw2WldSZllua2lPaUp1YjI5aVlXRWlMQ0pwWVhRaU9qRTFOalV4TmpNNU5EWjkuTzMxNU04cEtUbzM1Umo1M1c2SXFVemtWSFdTQ0hGNnJBM09DcDVFemxqWSIsInJvb3RfcGF0aCI6Ii4vbm9vYmFhX3N0b3JhZ2UvIn0="
            - name: ENDPOINT_PORT
              value: "6001"
            - name: ENDPOINT_SSL_PORT
              value: "6443"
          command: ["/noobaa_init_files/noobaa_init.sh", "agent"]
          # Insert the relevant image for the agent
          ports:
            # This should change according to the allocation from the NooBaa server
            - containerPort: 60101
          # These volume mounts are persistent. Each pod in the PetSet
          # gets a volume mounted based on this field.
          volumeMounts:
            - name: noobaastorage
              mountPath: /noobaa_storage
            - name: tmp-logs-vol
              mountPath: /usr/local/noobaa/logs
      volumes:
        - name: tmp-logs-vol
          emptyDir: {}
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  volumeClaimTemplates:
    - metadata:
        name: noobaastorage
        labels:
          app: noobaa
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 30Gi
        # Uncomment and add storageClass specific to your requirements below. Read more https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
        #storageClassName:

