apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephrbd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ocs-storagecluster-ceph-rbd
