apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ocs-storagecluster-cephfs
