apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  creationTimestamp: '2021-09-14T03:45:19Z'
  finalizers:
    - observability.open-cluster-management.io/res-cleanup
  generation: 3
  managedFields:
    - apiVersion: observability.open-cluster-management.io/v1beta2
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:advanced':
            .: {}
            'f:receive':
              .: {}
              'f:replicas': {}
              'f:resources':
                .: {}
                'f:limits':
                  .: {}
                  'f:memory': {}
            'f:retentionConfig':
              .: {}
              'f:blockDuration': {}
              'f:deleteDelay': {}
              'f:retentionResolution1h': {}
              'f:retentionResolution5m': {}
              'f:retentionResolutionRaw': {}
          'f:enableDownsampling': {}
          'f:observabilityAddonSpec':
            .: {}
            'f:enableMetrics': {}
            'f:interval': {}
          'f:storageConfig':
            .: {}
            'f:alertmanagerStorageSize': {}
            'f:compactStorageSize': {}
            'f:metricObjectStorage':
              .: {}
              'f:key': {}
              'f:name': {}
            'f:receiveStorageSize': {}
            'f:ruleStorageSize': {}
            'f:storageClass': {}
            'f:storeStorageSize': {}
      manager: kubectl-create
      operation: Update
      time: '2021-09-14T03:45:19Z'
    - apiVersion: observability.open-cluster-management.io/v1beta2
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            .: {}
            'v:"observability.open-cluster-management.io/res-cleanup"': {}
        'f:spec':
          'f:advanced':
            'f:receive':
              'f:resources':
                'f:limits':
                  'f:memory': {}
        'f:status':
          .: {}
          'f:conditions': {}
      manager: mco-operator
      operation: Update
      time: '2021-09-14T03:45:30Z'
    - apiVersion: observability.open-cluster-management.io/v1beta2
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:advanced':
            'f:retentionConfig':
              'f:retentionInLocal': {}
      manager: Mozilla
      operation: Update
      time: '2021-09-14T05:13:16Z'
  name: observability
  resourceVersion: '773821'
  uid: 592cfd58-26ef-44cf-95c2-77c9af398889
spec:
  #https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.3/html/apis/apis#observability-api
  #https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.3/html/observability/observing-environments-intro#persistent-stores-observability
  advanced:
    receive:
      replicas: 3
      resources:
        limits:
          memory: 4Ti
    retentionConfig:
      blockDuration: 2h #determines how long samples will be stored in memory before they are flushed (the default recommendation being 2h).
      deleteDelay: 12h #The amount of time until a block marked for deletion is deleted from a bucket.
      retentionInLocal: 2m # The amount of time to retain raw samples from the local storage.
      retentionResolution1h: 0d #Dont store 1h resolution in bucket
      retentionResolution5m: 180d #Store 5m resolution for 180d in bucket
      retentionResolutionRaw: 30d #Retain raw sample for 30d in bucket
  enableDownsampling: true
  observabilityAddonSpec:
    enableMetrics: true
    interval: 60
  storageConfig:
    alertmanagerStorageSize: 1Gi
    compactStorageSize: 100Gi #The amount of storage applied to the thanos compact stateful sets.
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
    receiveStorageSize: 100Gi #The amount of storage applied to thanos receive stateful sets.
    ruleStorageSize: 1Gi #The amount of storage applied to thanos rule stateful sets
    storageClass: gp2
    storeStorageSize: 10Gi #The amount of storage applied to thanos store stateful sets
status:
  conditions:
    - lastTransitionTime: '2021-09-14T03:45:30Z'
      message: Installation is in progress
      reason: Installing
      status: 'True'
      type: Installing
    - lastTransitionTime: '2021-09-14T03:58:01Z'
      message: Observability components are deployed and running
      reason: Ready
      status: 'True'
      type: Ready

