---
# tasks file for roles/configure_pxe_server
- name: Create PXE boot default directory
  file:
    path: "{{ item }}"
    state: directory
  tags:
    - configure_pxe_server
  when: inventory_hostname in groups['helper_vm']
  with_items:
    - "{{ pxe_image_directory }}"
    - "{{ pxe_boot_direcotry }}"

- name: Downloading RHCOS 4.1.0 initram
  get_url:
    url: "{{ rhcos_initramfs_url }}"
    dest: "{{ pxe_image_directory }}"
    timeout: 300
    validate_certs: false
  tags:
      - configure_pxe_server
      - download_image
  when: inventory_hostname in groups['helper_vm']

- name: Downloading RHCOS 4.1.0 kernel
  get_url:
    url: "{{ rhcos_kernel_url }}"
    dest: "{{ pxe_image_directory }}"
    validate_certs: false
    timeout: 300
  tags:
      - configure_pxe_server
      - download_image
  when: inventory_hostname in groups['helper_vm']

- name: Update /var/lib/tftpboot/pxelinux.cfg/default
  template:
    src: default.j2
    dest: /var/lib/tftpboot/pxelinux.cfg/default
  tags:
      - configure_pxe_server
  when: inventory_hostname in groups['helper_vm']

- name: Update /var/lib/tftpboot/pxelinux.cfg/bootstrap
  template:
    src: bootstrap.j2
    dest: '/var/lib/tftpboot/pxelinux.cfg/01-{{ hostvars[item]["vm_macaddress"] | replace(":", "-") | lower }}'
  tags:
      - configure_pxe_server
      - update_pxe_config
  when: inventory_hostname in groups['helper_vm']
  with_items: "{{ groups['ocp4_bootstrap_vm'] }}"

- name: Update /var/lib/tftpboot/pxelinux.cfg/master
  template:
    src: master.j2
    dest: '/var/lib/tftpboot/pxelinux.cfg/01-{{ hostvars[item]["vm_macaddress"] | replace(":", "-") | lower }}'
  tags:
      - configure_pxe_server
      - update_pxe_config
  when: "inventory_hostname in groups['helper_vm'] and item not in groups['ocp4_bootstrap_vm']"
  with_items: "{{ groups['ocp4_master_vm'] }}"

- name: Update /var/lib/tftpboot/pxelinux.cfg/worker
  template:
    src: worker.j2
    dest: '/var/lib/tftpboot/pxelinux.cfg/01-{{ hostvars[item]["vm_macaddress"] | replace(":", "-") | lower }}'
  tags:
      - configure_pxe_server
  when: inventory_hostname in groups['helper_vm']
  with_items: "{{ groups['ocp4_worker_vm'] }}"

- name: Copy file for PXE boot
  shell: cp -rvf /usr/share/syslinux/* /var/lib/tftpboot
  tags:
      - configure_pxe_server
  when: inventory_hostname in groups['helper_vm']

- name: Restore SELinux fcontext
  shell: restorecon -RFv "{{ item }}"
  tags:
      - configure_pxe_server
  when: inventory_hostname in groups['helper_vm']
  with_items:
    - "{{ pxe_image_directory }}"
    - "{{ pxe_boot_direcotry }}"

- name: Start TFTP services
  service:
    name: tftp
    state: restarted
    enabled: yes
  when: inventory_hostname in groups['helper_vm'] 
  tags:
      - configure_pxe_server
