---
- name: Preparing and Configuring DHCP and PXE Configs
  become: true
  hosts: helper_vm
  gather_facts: false
  roles:
    - configure_dhcpconfig
    - configure_pxeconfig
    - configure_lbconfig
    - configure_ignitionfiles
  vars_prompt:
    - name: redhat_pull_secret
      prompt: "Pull secret from cloud.redhat.com"
      private: no
    - name: core_ssh_publickey
      prompt: "Core SSH Public key"
      private: no
- name: Preparing and Deploying VM on Libvirt
  become: true
  vars:
    libvirt_storage_pool:
      - nvme-images
      - ssd-images
  hosts: all
  gather_facts: false
  roles:
    - configure_storage
    - deploy_ocpvms