apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcdbackup-nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs
    server: 192.168.254.201
  claimRef:
    name: etcdbackup-nfs-pvc
    namespace: bytewise-platform-mgmt