kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: compliance-hosting-pvc
  namespace: openshift-compliance
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: compliance-hosting-pv
  volumeMode: Filesystem