---
# tasks file for roles/configure_helper_binary
- name: Downloading {{ oc_install_url }}
  get_url:
    url: "{{ oc_install_url }}"
    dest: /usr/bin/
    validate_certs: false
    timeout: 300
  tags: 
    - configure_helper_binary

- name: Downloading {{ oc_client_url }}
  get_url:
    url: "{{ oc_client_url }}"
    dest: /usr/bin/
    validate_certs: false
    timeout: 300
  tags: 
    - configure_helper_binary

- name: Extracting downloaded installer binary
  shell: tar -C /usr/bin -xvf /usr/bin/openshift-install-linux-{{ openshift_version }}.tar.gz
  tags: 
    - configure_helper_binary

- name: Extracting downloaded client binary
  shell: tar -C /usr/bin -xvf /usr/bin/openshift-client-linux-{{ openshift_version }}.tar.gz
  tags: 
    - configure_helper_binary
