---
# tasks file for ../../ansible_libvirt_upi_bm/setup_helper_node/roles/pkgs_installer
- name: Ensure pkgs installed (RHEL 8)
  dnf:
    name: "{{ rhel8_pkgs }}"
    state: latest
  tags: initial_setup
  when: ansible_distribution_version|int == 8

- name: Ensure pkgs installed (RHEL 7)
  yum:
    name: "{{ rhel7_pkgs }}"
    state: latest
  tags: initial_setup
  when: ansible_distribution_version|int == 7
