---
# tasks file for roles/configure_vm_dns
- name: Configuring /etc/named/named.conf
  template:
    src: named.conf.j2
    dest: /etc/named.conf
  when: "'helper_vm' in group_names"
  tags:
    - configure_dns

- name: Configuring A zone files
  template:
    src: local.bytewise.my.db.j2
    dest: /var/named/local.bytewise.my.db
  when: "'helper_vm' in group_names"
  tags:
    - configure_dns

- name: Configuring PTR zone files
  template:
    src: 50.168.192.in-addr.arpa.db.j2
    dest: /var/named/50.168.192.in-addr.arpa.db
  when: "'helper_vm' in group_names"
  tags:
    - configure_dns


- name: Reload and enable bind server
  service:
    name: named
    state: restarted
    enabled: yes
  tags:
    - configure_dns
  when: inventory_hostname in groups['helper_vm']
