---
# tasks file for roles/update_haproxy_config

- name: Updating /etc/haproxy/haproxy.conf
  template:
    src: haproxy.conf.j2
    dest: /etc/haproxy/haproxy.cfg
  tags:
    - update_haproxy_config
  when: inventory_hostname in groups['helper_vm']

- name: Restart haproxy services
  service:
    name: haproxy
    state: restarted
    enabled: yes
  when: inventory_hostname in groups['helper_vm'] 
  tags:
    - update_haproxy_config
