---
# tasks file for roles/selinux_rules
- name: Allowing haproxy to bind to alternate port
  seport:
    ports: "{{ item }}"
    setype: http_port_t
    state: present
    proto: tcp
  when: inventory_hostname in groups['helper_vm']
  with_items: "{{ allowed_http_port_t }}"