---
# tasks file for roles/update_idmdns_server
- name: Update IdM master A DNS Record
  delegate_to: localhost
  ipa_dnsrecord:
    ipa_host: idm.bytewise.com.my
    ipa_user: admin
    ipa_pass: '{{ ipa_password }}'
    state: present
    zone_name: bytewise.com.my
    record_type: A
    record_name: "{{ inventory_hostname.split('.')[0] }}.{{ openshift_domain | trim }}"
    record_value: "{{ vm_ipaddress }}"
    validate_certs: no
  when: inventory_hostname in groups['ocp4_master_vm']
  tags:
    - update_idmdns_server

- name: Update IdM master PTR DNS Record
  delegate_to: localhost
  ipa_dnsrecord:
    ipa_host: idm.bytewise.com.my
    ipa_user: admin
    ipa_pass: '{{ ipa_password }}'
    state: present
    zone_name: 50.168.192.in-addr.arpa
    record_type: PTR
    record_name: "{{ vm_ipaddress.split('.')[3] | trim }}"
    record_value: "{{ inventory_hostname}}."
    validate_certs: no
  when: inventory_hostname in groups['ocp4_master_vm']
  tags:
    - update_idmdns_server

- name: Update IdM router/worker PTR DNS Record
  delegate_to: localhost
  ipa_dnsrecord:
    ipa_host: idm.bytewise.com.my
    ipa_user: admin
    ipa_pass: '{{ ipa_password }}'
    state: present
    zone_name: 50.168.192.in-addr.arpa
    record_type: PTR
    record_name: "{{ vm_ipaddress.split('.')[3] | trim }}"
    record_value: "{{ inventory_hostname }}."
    validate_certs: no
  when: inventory_hostname in groups['ocp4_router_vm']
  tags:
    - update_idmdns_server

- name: Update IdM Router DNS Record
  delegate_to: localhost
  ipa_dnsrecord:
    ipa_host: idm.bytewise.com.my
    ipa_user: admin
    ipa_pass: '{{ ipa_password }}'
    state: present
    zone_name: bytewise.com.my
    record_type: A
    record_name: "{{ inventory_hostname.split('.')[0] }}.{{ openshift_domain | trim }}"
    record_value: "{{ vm_ipaddress }}"
    validate_certs: no
  when: inventory_hostname in groups['ocp4_router_vm']
  tags:
    - update_idmdns_server

- name: Update IdM API DNS Record
  delegate_to: localhost
  ipa_dnsrecord:
    ipa_host: idm.bytewise.com.my
    ipa_user: admin
    ipa_pass: '{{ ipa_password }}'
    state: present
    zone_name: bytewise.com.my
    record_type: A
    record_name: api.{{ openshift_domain }}
    record_value: "{{ vm_ipaddress }}"
    validate_certs: no
  when: inventory_hostname in groups['helper_vm']
  tags: update_dns

- name: Update IdM API-INT DNS Record
  delegate_to: localhost
  ipa_dnsrecord:
    ipa_host: idm.bytewise.com.my
    ipa_user: admin
    ipa_pass: '{{ ipa_password }}'
    state: present
    zone_name: bytewise.com.my
    record_type: A
    record_name: api-int.{{ openshift_domain }}
    record_value: "{{ vm_ipaddress }}"
    validate_certs: no
  when: inventory_hostname in groups['helper_vm']
  tags: update_dns

- name: Update IdM Wildcard DNS Record
  delegate_to: localhost
  ipa_dnsrecord:
    ipa_host: idm.bytewise.com.my
    ipa_user: admin
    ipa_pass: '{{ ipa_password }}'
    state: present
    zone_name: bytewise.com.my
    record_type: A
    record_name: \*.{{ openshift_domain }}
    record_value: "{{ vm_ipaddress }}"
    validate_certs: no
  when: inventory_hostname in groups['helper_vm']
  tags: update_dns

- name: Update IdM etcd-0 DNS Record
  delegate_to: localhost
  ipa_dnsrecord:
    ipa_host: idm.bytewise.com.my
    ipa_user: admin
    ipa_pass: '{{ ipa_password }}'
    state: present
    zone_name: bytewise.com.my
    record_type: A
    record_name: etcd-0.ocp4
    record_value: "{{ vm_ipaddress }}"
    validate_certs: no
  when: inventory_hostname in groups['ocp4_master_vm'][1] and "bootstrap" not in inventory_hostname
  tags:
    - update_idmdns_server

- name: Update IdM etcd-1 DNS Record
  delegate_to: localhost
  ipa_dnsrecord:
    ipa_host: idm.bytewise.com.my
    ipa_user: admin
    ipa_pass: '{{ ipa_password }}'
    state: present
    zone_name: bytewise.com.my
    record_type: A
    record_name: etcd-1.ocp4
    record_value: "{{ vm_ipaddress }}"
    validate_certs: no
  when: inventory_hostname in groups['ocp4_master_vm'][2] and "bootstrap" not in inventory_hostname
  tags:
    - update_idmdns_server

- name: Update IdM etcd-2 DNS Record
  delegate_to: localhost
  ipa_dnsrecord:
    ipa_host: idm.bytewise.com.my
    ipa_user: admin
    ipa_pass: '{{ ipa_password }}'
    state: present
    zone_name: bytewise.com.my
    record_type: A
    record_name: etcd-2.ocp4
    record_value: "{{ vm_ipaddress }}"
    validate_certs: no
  when: inventory_hostname in groups['ocp4_master_vm'][3] and "bootstrap" not in inventory_hostname
  tags:
    - update_idmdns_server

- name: Ensure _etcd-server-ssl._tcp.ocp4 exists in IdM ldap
  delegate_to: localhost
  ldap_entry:
    dn: "idnsname=_etcd-server-ssl._tcp.ocp4,idnsname=bytewise.com.my.,cn=dns,dc=bytewise,dc=com,dc=my"
    state: present
    server_uri: ldap://idm.bytewise.com.my/
    bind_dn: uid=admin,cn=users,cn=accounts,dc=bytewise,dc=com,dc=my
    bind_pw: '{{ ipa_password }}'
    validate_certs: false
    objectClass:
      - top
      - idnsrecord
  ignore_errors: true
  tags:
    - update_idmdns_server
    
- name: Update _etcd-server-ssl._tcp.ocp4 record
  delegate_to: localhost
  ldap_attr:
    dn: idnsname=_etcd-server-ssl._tcp.ocp4,idnsname=bytewise.com.my.,cn=dns,dc=bytewise,dc=com,dc=my
    name: sRVRecord
    values: ["0 10 2380 etcd-0.ocp4", "0 10 2380 etcd-1.ocp4", "0 10 2380 etcd-2.ocp4"]
    server_uri: ldap://idm.bytewise.com.my/
    bind_dn: uid=admin,cn=users,cn=accounts,dc=bytewise,dc=com,dc=my
    bind_pw: redhat123
    validate_certs: false
  tags:
    - update_idmdns_server