

apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging02
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 192.168.50.1:3260
     iqn: iqn.2003-01.org.linux-iscsi.mzali-fedora.x8664:sn.e4ca6560246a
     lun: 2
     fsType: 'ext4'
     readOnly: false
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    namespace: openshift-logging
    name: elasticsearch-elasticsearch-cdm-39tycaie-2


