apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: IdMLDAP 
    mappingMethod: claim 
    type: LDAP
    ldap:
      attributes:
        id: 
        - dn
        email: 
        - mail
        name: 
        - cn
        preferredUsername: 
        - uid
      bindDN: "uid=mzali,cn=users,cn=accounts,dc=local,dc=bytewise,dc=my" 
      bindPassword: 
        name: ldap-secret
      insecure: true
      url: "ldap://idm.local.bytewise.my/cn=users,cn=accounts,dc=local,dc=bytewise,dc=my?uid"

