---
- name: Preparing & Configuring Helper Node
  become: true
  hosts: helper_vm
  vars_prompt:
    - name: redhat_pull_secret
      prompt: "Pull secret from cloud.redhat.com"
      private: no
    - name: core_ssh_publickey
      prompt: "Core SSH Public key"
      private: no
  gather_facts: true
  roles:
   - install_pkgs
   - configure_firewall
   - configure_selinux
   - configure_http
   - configure_pxe
   - configure_ocpcli
