apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-ceph-flexvolume 
spec:
  capacity:
    storage: 100Gi 
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: ceph.rook.io/rook 
    fsType: "ceph" 
    readOnly: false 
    options: 
      clusterNamespace: rook-ceph
      fsName: registry-cephfs
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    namespace: openshift-image-registry
    name: image-registry-storage 
