allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
groups:
- system:authenticated
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: Custom restricted (added flexVolume type) denies access
      to all host features and requires pods to be run with a UID, and SELinux context
      that are allocated to the namespace.  This is the most restrictive SCC and it
      is used by default for authenticated users.
  creationTimestamp: "2019-08-29T06:45:11Z"
  generation: 1
  name: custom-restricted-with-flexvolume
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:openshift-image-registry:registry
volumes:
- configMap
- downwardAPI
- emptyDir
- flexVolume
- persistentVolumeClaim
- projected
- secret
