---
- name: Libvirt VMs
  vars:
    redhat_pull_secret: ''
    core_ssh_publickey: ''
    openshift_version: 4.1.8
    openshift_domain: ocp4
    libvirt_storage_pool:
      - default
      - fastdisk
  vars_prompt:
    - name: ipa_password
      prompt: "Please enter admin password for IdM"
      private: yes
  hosts: all
  gather_facts: false
  roles:
    - update_idmdns_server
    - update_dhcpd_config
    - {role: configure_pxe_server, tags: ['update_pxe_config']}
    - update_haproxy_config
    - configure_ocp_cli_binary
    - configure_ignitions_file
    - provisioning_libvirt
