
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  name: ubi8
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.redhat.io/ubi8/ubi:latest
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: oclientubi8
  namespace: serving-cert-approver-workaround
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    name: docker-build
  name: docker-build
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: oclientubi8:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: serving-cert-approver-workaround
    git:
      uri: https://github.com/aizuddin85/openshift4.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
      env:
      - name: OC_VERSION
        value: 4.1.13
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - type: ConfigChange
